In [1]:
import numpy as np
import pandas as pd

In [2]:
# https://www.kaggle.com/rodolfofigueroa/spotify-12m-songs
data = pd.read_csv('tracks_features.csv')

In [3]:
data = data[['name', 'album', 'album_id', 'artists', 'track_number', 'disc_number']]

In [4]:
data

,name,album,album_id,artists,track_number,disc_number
0,Testify,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],1,1
1,Guerrilla Radio,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],2,1
2,Calm Like a Bomb,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],3,1
3,Mic Check,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],4,1
4,Sleep Now In the Fire,The Battle Of Los Angeles,2eia0myWFgoHuttJytCxgX,['Rage Against The Machine'],5,1
...,...,...,...,...,...,...
1204020,Gospel of Juke,Notch - EP,38O5Ys0W9PFS5K7dMb7yKb,['FVLCRVM'],2,1
1204021,Prism Visions,Notch - EP,38O5Ys0W9PFS5K7dMb7yKb,['FVLCRVM'],3,1
1204022,Tokyo 360,Notch - EP,38O5Ys0W9PFS5K7dMb7yKb,['FVLCRVM'],4,1
1204023,Yummy!,Notch - EP,38O5Ys0W9PFS5K7dMb7yKb,['FVLCRVM'],5,1
1204024,That's The Way It Is,Notch - EP,38O5Ys0W9PFS5K7dMb7yKb,['FVLCRVM'],6,1

In [5]:
data.rename(columns={'name': 'song'}, inplace=True)

In [6]:
data['album_id'].unique().size #118382 total albums

118382

In [7]:
data['album'].value_counts().head(60)

Greatest Hits                            1800
Live                                      872
The Collection                            343
Love Songs                                337
Super Hits                                330
Platinum & Gold Collection                300
The Best Of                               280
RCA 100 Años de Música                    280
II                                        278
Handel: Messiah                           268
Best Of                                   255
The Definitive Collection                 249
Home                                      240
One                                       230
III                                       227
16 Most Requested Songs                   224
Rise                                      202
Live at Billy Bob's Texas                 196
Full Circle                               184
Gold                                      184
Orff: Carmina Burana                      177
Christmas                                 171
The Early Years                           166
Forever                                   165
Shine                                     164
RCA 100 Años De Musica                    160
Anthology                                 158
The Very Best Of                          158
Moments                                   155
It's About Time                           154
Deluxe Edition                            153
Ghosts                                    153
Beethoven: The Complete Piano Sonatas     150
Believe                                   148
IV                                        147
Nur das Beste                             147
The Singles                               146
Free                                      146
Evolution                                 143
Reflections                               142
Life                                      141
Seasons                                   136
Still                                     136
Spirit                                    135
The Ultimate Collection                   135
EP                                        134
Split                                     134
Grace                                     133
Unplugged                                 133
Better Days                               130
X                                         130
Renaissance                               129
Freedom                                   129
Genesis                                   124
Britten: Albert Herring                   123
Redemption                                123
Higher Ground                             122
2                                         122
Balance                                   121
Retrospective                             120
Name: album, dtype: int64

In [8]:
data['album_id'].value_counts() # Greatest hits compilations, singles, EPs?

3CaePe3lnlUuJNJyXQKHyJ    50
2uXGYxyBP2xMouxfKnfhip    50
0tDRflyTKSHd35WSdqksWY    50
53kHQtLdbgfrDUsmnCv4eK    50
0MKh0qwcyd2YTpzRAFmV6O    50
                          ..
1kgS1kXwRL0C508nRRNLkR     1
10bxt7UJMyOFEm4LWzuzST     1
4gWX3HriDmej4AS8vE4Bh0     1
1L7pG1ISGo71iOexMfk9Wn     1
3ZcNvUumi8GP1m7BzKdYQ7     1
Name: album_id, Length: 118382, dtype: int64

In [9]:
album_lengths = data.groupby('album_id').agg({'track_number':['max']})

In [10]:
album_lengths.value_counts() # Singles are the most common album, 20994 of them

(track_number, max)
1                      20994
10                     12004
12                     11509
11                     10057
13                      7081
14                      5862
9                       5713
8                       4908
15                      4231
5                       3845
6                       3802
7                       3569
4                       3466
16                      3352
2                       2902
3                       2152
17                      2146
18                      1993
20                      1608
19                      1262
21                       954
22                       707
24                       590
25                       576
23                       572
26                       359
30                       279
27                       277
28                       235
50                       208
29                       195
32                       138
31                       119
33                       105
40                        85
34                        66
35                        66
36                        60
37                        59
42                        46
38                        46
39                        31
48                        26
45                        24
41                        21
43                        20
44                        20
46                        16
47                        14
49                        12
dtype: int64

In [13]:
# Focus on albums between 8 and 16 tracks
LP_ids = album_lengths[album_lengths[('track_number', 'max')].isin(range(8,17))].index # still a lot of live albums and stuff

In [14]:
LP_ids.size # 63227 for 8 to 16 length albums, 64717 if ignoring disc 2+

64717

In [15]:
# Just deal with it I guess
LPs = data.loc[data['album_id'].isin(LP_ids)]

In [16]:
LPs.groupby('album_id').agg({'track_number':['max']}).value_counts()

(track_number, max)
10                     12004
12                     11509
11                     10057
13                      7081
14                      5862
9                       5713
8                       4908
15                      4231
16                      3352
dtype: int64

In [24]:
#title_tracks = LPs.loc[LPs['name'] == LPs['album']]
title_tracks = LPs[LPs.apply(lambda x: x.album in x.song or x.song in x.album, axis=1)] # little slow

In [25]:
title_tracks #17303 for exact match #20421 for song IN album #23636 for album IN song #26754 for either

,song,album,album_id,artists,track_number,disc_number
23,Do It for Love,Do It for Love,4evw6IBex3N8x1oA2axMTH,['Daryl Hall & John Oates'],2,1
77,Rosaryville,Rosaryville,747XdfKqkymjuvap8Lm1Hv,['Kate Campbell'],1,1
130,Dilate,Dilate,4KE4xztIchTBItYOnCT3FU,['Ani DiFranco'],4,1
168,Imperfectly,Imperfectly,6yIQT5AvjFQ0kRo3RxBN6n,['Ani DiFranco'],13,1
212,Red Moon,Live Under the Red Moon,49IfAdGx0aRX0N7QSUaNsM,['The Call'],9,1
...,...,...,...,...,...,...
1203799,High Gravity,High Gravity,1CeTc9vwXkjvtY7kaM1zF5,['Revolt Production Music'],9,1
1203871,Genesis XIX,Genesis XIX,4iI1Qvmfy5BPAW0Z1eQ9dt,['Sodom'],4,1
1203916,Ente,Ente,3ny3ebCbCblTWLBsAukYTk,['Descarnado'],7,1
1203921,Niño Zombi,Niño Zombi,32pch13KvUCPUZ3H2Icxdv,['Descarnado'],3,1
1203955,Christmas Blues,Christmas Blues,1wYxighrXciRyM6KjF5Gv2,"['Sabrina Claudio', 'The Weeknd']",3,1

In [26]:
title_tracks['track_number'].value_counts()

1     6531
2     3107
3     2523
4     2084
5     1907
6     1783
8     1534
7     1522
9     1327
10    1315
11    1054
12     918
13     507
14     340
15     200
16     102
Name: track_number, dtype: int64

In [27]:
title_tracks.to_csv('title_tracks.csv')

In [ ]:
# Many problems with testing for title track
# Might find two+ title tracks for an album (ex. two versions on same release, or album title is just a letter (yes there was one))

In [23]:
data.loc[data['album'].str.contains('soundtrack', case=False)]

,song,album,album_id,artists,track_number,disc_number
3850,I'm Your Man,Secretary (Original Motion Picture Soundtrack),4HiD2iP9HRoUyrXYz9fGHT,['Leonard Cohen'],1,1
3851,Main Title,Secretary (Original Motion Picture Soundtrack),4HiD2iP9HRoUyrXYz9fGHT,['Angelo Badalamenti'],2,1
3852,Feelin' Free,Secretary (Original Motion Picture Soundtrack),4HiD2iP9HRoUyrXYz9fGHT,['Angelo Badalamenti'],3,1
3853,Snow Dome Dreams,Secretary (Original Motion Picture Soundtrack),4HiD2iP9HRoUyrXYz9fGHT,['Angelo Badalamenti'],4,1
3854,Bathing Blossom,Secretary (Original Motion Picture Soundtrack),4HiD2iP9HRoUyrXYz9fGHT,['Angelo Badalamenti'],5,1
...,...,...,...,...,...,...
1202999,If Walls Could Talk - Words on Bathroom Walls,Words on Bathroom Walls (Original Motion Pictu...,0sEhMYq3QFy3ShBGzUO2wu,['The Chainsmokers'],16,1
1203000,Letter - Words on Bathroom Walls,Words on Bathroom Walls (Original Motion Pictu...,0sEhMYq3QFy3ShBGzUO2wu,"['Andrew Hollander', 'The Chainsmokers']",17,1
1203001,Adam's Speech Part 2 - Words on Bathroom Walls,Words on Bathroom Walls (Original Motion Pictu...,0sEhMYq3QFy3ShBGzUO2wu,"['Andrew Hollander', 'The Chainsmokers']",18,1
1203002,The Kiss - Words on Bathroom Walls,Words on Bathroom Walls (Original Motion Pictu...,0sEhMYq3QFy3ShBGzUO2wu,"['Andrew Hollander', 'The Chainsmokers']",19,1
1203038,Rise of the Demonitizer Soundtrack,Rise of the Demonitizer Soundtrack,1j9siwQUJLCb9qzZip8ZI0,['Lilnah'],1,1

In [ ]:
data.loc[data['album'].str.contains('hits', case=False)]

In [ ]:
data.loc[data['album'].str.contains('retrospective', case=False)]

In [ ]:
data.loc[data['name'].str.contains('feat', case=False)]

In [36]:
title_track_placement = title_tracks.copy()

In [37]:
title_track_placement['disc_number'].value_counts()

1    26360
2      358
3       34
4        2
Name: disc_number, dtype: int64

In [38]:
# just ignore discs past 1 i guess
title_track_placement = title_track_placement[title_track_placement['disc_number'] == 1]

In [30]:
album_lengths

                       track_number
                                max
album_id
0008WZMLnvEBVnq418uZsI            3
000LUYjGxRJ3mHl1pD2xPQ            8
000Ok2jIbYSMb16yzbAZrV            1
001HdcL1YDEhlxMlQvvnCk            1
001evNEnBGO2FDbedRyZLo            7
...                             ...
7zzQIYXxfr0A8mg1hhd2SQ            1
7zza0SWpmcMywSdT2yHndC           16
7zzkNlCuvlF6qgio59qmSc           10
7zzqZmWw32Kb5snPXxL2nI            1
7zzz0Fqahwtd6jd2BgBFj6           10

[118382 rows x 1 columns]

In [49]:
title_track_placement.set_index('album_id', inplace = True)

In [50]:
title_track_placement['num_tracks'] = album_lengths['track_number']['max']

In [51]:
title_track_placement

,song,album,artists,track_number,disc_number,num_tracks
album_id,,,,,,
4evw6IBex3N8x1oA2axMTH,Do It for Love,Do It for Love,['Daryl Hall & John Oates'],2,1,14
747XdfKqkymjuvap8Lm1Hv,Rosaryville,Rosaryville,['Kate Campbell'],1,1,10
4KE4xztIchTBItYOnCT3FU,Dilate,Dilate,['Ani DiFranco'],4,1,11
6yIQT5AvjFQ0kRo3RxBN6n,Imperfectly,Imperfectly,['Ani DiFranco'],13,1,13
49IfAdGx0aRX0N7QSUaNsM,Red Moon,Live Under the Red Moon,['The Call'],9,1,13
...,...,...,...,...,...,...
1CeTc9vwXkjvtY7kaM1zF5,High Gravity,High Gravity,['Revolt Production Music'],9,1,10
4iI1Qvmfy5BPAW0Z1eQ9dt,Genesis XIX,Genesis XIX,['Sodom'],4,1,12
3ny3ebCbCblTWLBsAukYTk,Ente,Ente,['Descarnado'],7,1,9
32pch13KvUCPUZ3H2Icxdv,Niño Zombi,Niño Zombi,['Descarnado'],3,1,9
1wYxighrXciRyM6KjF5Gv2,Christmas Blues,Christmas Blues,"['Sabrina Claudio', 'The Weeknd']",3,1,8

In [53]:
title_track_placement['from_bottom'] = title_track_placement['num_tracks'] - title_track_placement['track_number'] + 1

In [54]:
title_track_placement

,song,album,artists,track_number,disc_number,num_tracks,from_bottom
album_id,,,,,,,
4evw6IBex3N8x1oA2axMTH,Do It for Love,Do It for Love,['Daryl Hall & John Oates'],2,1,14,13
747XdfKqkymjuvap8Lm1Hv,Rosaryville,Rosaryville,['Kate Campbell'],1,1,10,10
4KE4xztIchTBItYOnCT3FU,Dilate,Dilate,['Ani DiFranco'],4,1,11,8
6yIQT5AvjFQ0kRo3RxBN6n,Imperfectly,Imperfectly,['Ani DiFranco'],13,1,13,1
49IfAdGx0aRX0N7QSUaNsM,Red Moon,Live Under the Red Moon,['The Call'],9,1,13,5
...,...,...,...,...,...,...,...
1CeTc9vwXkjvtY7kaM1zF5,High Gravity,High Gravity,['Revolt Production Music'],9,1,10,2
4iI1Qvmfy5BPAW0Z1eQ9dt,Genesis XIX,Genesis XIX,['Sodom'],4,1,12,9
3ny3ebCbCblTWLBsAukYTk,Ente,Ente,['Descarnado'],7,1,9,3
32pch13KvUCPUZ3H2Icxdv,Niño Zombi,Niño Zombi,['Descarnado'],3,1,9,7
1wYxighrXciRyM6KjF5Gv2,Christmas Blues,Christmas Blues,"['Sabrina Claudio', 'The Weeknd']",3,1,8,6

In [56]:
title_track_placement['from_bottom'].value_counts()

1     2799
10    2671
9     2356
8     2310
11    2190
7     1956
12    1835
6     1727
5     1560
2     1553
4     1399
3     1305
13    1128
14     833
15     475
16     263
Name: from_bottom, dtype: int64

In [65]:
title_track_placement[title_track_placement['num_tracks'] == 8]['track_number'].value_counts()

1    496
2    263
8    256
3    233
4    216
5    193
6    172
7    163
Name: track_number, dtype: int64

In [66]:
title_track_placement[title_track_placement['num_tracks'] == 9]['track_number'].value_counts()

1    574
9    313
2    306
3    252
4    222
5    205
6    203
8    189
7    171
Name: track_number, dtype: int64

In [58]:
title_track_placement[title_track_placement['num_tracks'] == 10]['track_number'].value_counts()

1     1295
2      600
10     528
3      467
4      421
6      377
5      373
9      278
7      262
8      253
Name: track_number, dtype: int64

In [59]:
title_track_placement[title_track_placement['num_tracks'] == 11]['track_number'].value_counts()

1     1087
2      479
11     474
3      430
5      356
4      346
6      286
7      235
10     232
8      220
9      181
Name: track_number, dtype: int64

In [60]:
title_track_placement[title_track_placement['num_tracks'] == 12]['track_number'].value_counts()

1     1156
2      549
12     503
3      435
4      333
6      304
5      281
7      253
11     248
8      204
10     201
9      189
Name: track_number, dtype: int64

In [61]:
title_track_placement[title_track_placement['num_tracks'] == 13]['track_number'].value_counts()

1     678
2     318
3     278
13    272
4     201
5     186
12    185
6     161
8     149
7     143
10    130
11    125
9     118
Name: track_number, dtype: int64

In [62]:
title_track_placement[title_track_placement['num_tracks'] == 14]['track_number'].value_counts()

1     588
2     261
14    211
3     190
4     138
7     134
5     128
13    125
6     115
9     110
8     100
12     98
10     97
11     87
Name: track_number, dtype: int64

In [63]:
title_track_placement[title_track_placement['num_tracks'] == 15]['track_number'].value_counts()

1     348
2     164
15    140
3     116
4     100
14     77
5      76
8      70
12     68
6      68
7      62
9      59
11     56
13     55
10     48
Name: track_number, dtype: int64

In [64]:
title_track_placement[title_track_placement['num_tracks'] == 16]['track_number'].value_counts()

1     263
2     127
16    102
3      81
4      73
5      71
7      65
6      62
10     58
15     56
8      56
11     53
12     52
14     49
9      49
13     47
Name: track_number, dtype: int64